language: python
python:
  - "3.6"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
script:
  - pytest lessons/functions/tests
  - pytest lessons/types/tests
branches:
  only:
    - master
    - development
